const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const tg=window.Telegram?.WebApp;const P=window.__MAXINES_PRODUCTS__||[];const H=window.__MAXINES_HEALTH__||{};const S=window.__MAXINES_SESSION__||{};const E=window.__ARCHIVE_EDITORIAL__||{};
const CURATED=['SHRT-89','OUT-014','GRF-101','BSC-06','OUT-012','PRT-003','PRT-002','GRF-102'];
let entered=sessionStorage.getItem('archive_entered')==='1',open=null,showBag=false,mediaMode='editorial',searchOpen=false,q='',toast='',requestState=null;
let bag=(()=>{try{return JSON.parse(localStorage.getItem('maxines_cart_v1')||'[]')}catch{return[]}})();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const product=sku=>P.find(p=>p.sku===sku);const editorial=p=>E[p.sku]||p.imageUrl;const original=p=>p.imageUrl||E[p.sku]||'';
const sourceLabel=p=>`${Number(p.displayPrice)%1?Number(p.displayPrice).toFixed(2):Number(p.displayPrice)} ${p.displayCurrency}`;
const safeDescriptor=p=>({
 'SHRT-89':'Statement print · contrast collar.',
 'OUT-014':'Plaid tailoring · dark shoulder accent.',
 'GRF-101':'Graphic tee · lace-up shoulder detail.',
 'BSC-06':'Deep burgundy · essential layer.',
 'OUT-012':'Bold color · brass hardware.',
 'PRT-003':'Wrap silhouette · statement print.',
 'PRT-002':'Leopard print · easy shape.',
 'GRF-102':'Texture · graphic and edgy.'
}[p.sku]||p.tag||p.category||'Source-backed archive piece.');
function saveBag(){localStorage.setItem('maxines_cart_v1',JSON.stringify(bag))}
function bagCount(){return bag.reduce((n,i)=>n+(Number(i.qty)||1),0)}
function curated(){const ordered=CURATED.map(product).filter(Boolean),seen=new Set(ordered.map(p=>p.sku));return [...ordered,...P.filter(p=>!seen.has(p.sku))]}
function visible(){const term=q.trim().toLowerCase();return curated().filter(p=>!term||`${p.name} ${p.sku} ${p.category} ${p.tag}`.toLowerCase().includes(term))}
function liveVariant(p){return p.variants?.find(v=>v.enabled&&v.inStock)||p.variants?.find(v=>v.enabled)||null}
function availability(p){return p.checkoutEnabled&&p.variants?.some(v=>v.enabled&&v.inStock)?'Available':'Availability on request'}
function commerceMode(){return H.checkoutActivated?'checkout':'request'}
function openProduct(p){open=p;mediaMode='editorial';showBag=false;requestState=null;tg?.HapticFeedback?.impactOccurred?.('light');syncBack();render()}
function closeOverlay(){open=null;showBag=false;requestState=null;syncBack();render()}
function syncBack(){try{if(open||showBag){tg?.BackButton?.show();tg.BackButton.onClick(closeOverlay)}else{tg?.BackButton?.hide();tg?.BackButton?.offClick?.(closeOverlay)}}catch{}}
function renderLanding(){const hero=product('SHRT-89')||curated()[0];const img=hero?editorial(hero):'';$('#app').innerHTML=`<section class="entry" id="enterArchive"><img class="entry-img" src="${img}" alt=""><div class="entry-shade"></div><div class="entry-meta"><span>MAXINES</span><span>Private Access</span></div><div class="entry-copy"><div class="entry-eyebrow">The Manila Edit</div><h1>Archive</h1><p>Vol. I — A private selection</p></div><div class="entry-enter"><span>Tap to Enter</span><i></i></div></section>`;$('#enterArchive').onclick=()=>{entered=true;sessionStorage.setItem('archive_entered','1');tg?.HapticFeedback?.impactOccurred?.('soft');render()}}
function card(p,i,total){return `<article class="look" data-sku="${esc(p.sku)}"><button class="look-media" data-open="${esc(p.sku)}" aria-label="Open ${esc(p.name)}"><img loading="lazy" src="${editorial(p)}" alt="${esc(p.name)} editorial presentation"><span class="media-badge">${E[p.sku]?'Studio View':'Original View'}</span></button><div class="look-copy"><div class="look-index">${String(i+1).padStart(2,'0')} / ${String(total).padStart(2,'0')}</div><h2>${esc(p.name)}</h2><p>${esc(safeDescriptor(p))}</p><div class="look-foot"><span>${esc(sourceLabel(p))} · source label</span><button data-open="${esc(p.sku)}">Discover →</button></div></div></article>`}
function renderHome(){const items=visible();$('#app').innerHTML=`<div class="archive-shell"><header class="archive-header"><button id="searchBtn" class="text-btn" aria-label="Search">Search</button><div class="wordmark"><span>MAXINES</span><b>Archive</b></div><button id="bagBtn" class="text-btn">Bag (${bagCount()})</button></header><main><section class="intro"><div class="intro-kicker">Vol. I · The Manila Edit</div><h1>A highly considered selection of foundational garments.</h1><p>Studio presentation paired with the untouched source image for trust.</p></section><section class="search-panel ${searchOpen?'is-open':''}"><input id="searchInput" value="${esc(q)}" placeholder="Search the archive" aria-label="Search the archive"><button id="searchClose">Close</button></section><section class="edit-list">${items.length?items.map((p,i)=>card(p,i,items.length)).join(''):`<div class="empty-state"><h2>No pieces found.</h2><p>Try another title, category, or SKU.</p></div>`}</section><footer class="archive-footer"><span>End of Edit</span><p>New pieces appear only after source reconciliation and review.</p></footer></main>${toast?`<div class="toast">${esc(toast)}</div>`:''}</div>${open?renderPdp(open):''}${showBag?renderBag():''}`;wireHome()}
function detailRows(p){const v=liveVariant(p);return `<div class="facts"><div><small>Category</small><strong>${esc(p.category||'Not specified')}</strong></div><div><small>Availability</small><strong>${esc(availability(p))}</strong></div><div><small>Size</small><strong>${esc(v?.size||'Not specified')}</strong></div><div><small>Source</small><strong>${p.sourceVerified?'Verified source record':'Needs review'}</strong></div></div>`}
function renderPdp(p){const img=mediaMode==='original'?original(p):editorial(p);const hasEditorial=Boolean(E[p.sku]);return `<div class="pdp-overlay"><div class="pdp-top"><button id="pdpBack" aria-label="Back">←</button><span>Archive Details</span><i></i></div><div class="pdp-scroll"><section class="pdp-hero"><img src="${img}" alt="${esc(p.name)} ${mediaMode==='original'?'original source photo':'editorial presentation'}"><div class="trust-toggle"><button data-media="editorial" class="${mediaMode==='editorial'?'active':''}" ${hasEditorial?'':'disabled'}>Editorial</button><button data-media="original" class="${mediaMode==='original'?'active':''}">Original Photo</button></div></section><section class="pdp-info"><div class="pdp-kicker">${esc(p.sku)} · ${esc(p.category||'Archive')}</div><h1>${esc(p.name)}</h1><p class="pdp-story">${esc(p.description||safeDescriptor(p))}</p>${detailRows(p)}<div class="source-price"><small>Source display label</small><strong>${esc(sourceLabel(p))}</strong><p>Shown exactly as recorded in the source catalog. It is not treated as an approved settlement price.</p></div><button class="primary" id="addSelection">Add to Selection</button><button class="secondary" id="openBagFromPdp">${commerceMode()==='checkout'?'Continue to checkout':'Request availability'}</button></section></div></div>`}
function bagItem(i,n){const p=product(i.sku)||i;return `<div class="reservation-item"><img src="${editorial(p)||i.imageUrl||''}" alt=""><div><h3>${esc(i.name||p.name)}</h3><p>${esc(i.sku)} · ${esc(i.size||'OS')} · ${esc(sourceLabel(i))}</p><div class="qty"><button data-qty="-1" data-i="${n}">−</button><span>${i.qty}</span><button data-qty="1" data-i="${n}">+</button></div></div></div>`}
function renderBag(){const live=commerceMode()==='checkout';return `<div class="drawer-backdrop" id="drawerBackdrop"><section class="drawer" role="dialog" aria-modal="true"><div class="drawer-handle"></div><button class="drawer-close" id="drawerClose">×</button><div class="drawer-title"><small>MAXINES Archive</small><h2>${live?'Your Selection':'Availability Request'}</h2><p>${live?'Your selected pieces are ready for secure checkout.':'Submit your selected pieces for verification. This is not a confirmed order and no payment will be taken.'}</p></div>${bag.length?`<div class="reservation-list">${bag.map(bagItem).join('')}</div><div class="drawer-note"><span class="status-dot"></span><div><strong>${live?'Secure checkout gates verified':'Verification required'}</strong><p>${live?'Totals are calculated server-side.':'MAXINES must confirm live stock and pricing before any sale can proceed.'}</p></div></div><button class="primary" id="drawerAction">${live?'Continue in Telegram':'Request Availability'}</button>${requestState?`<div class="request-state ${requestState.type}">${esc(requestState.text)}</div>`:''}`:`<div class="empty-state"><h2>Your selection is empty.</h2><p>Discover a piece and add it here.</p></div>`}</section></div>`}
function addToBag(p){const size=liveVariant(p)?.size||'OS';let x=bag.find(i=>i.sku===p.sku&&i.size===size);if(x)x.qty=Math.min(10,(x.qty||1)+1);else bag.push({sku:p.sku,name:p.name,size,displayPrice:Number(p.displayPrice),displayCurrency:p.displayCurrency,imageUrl:original(p),qty:1});saveBag();toast='Added to your selection.';tg?.HapticFeedback?.impactOccurred?.('medium');showBag=true;open=null;syncBack();render();setTimeout(()=>{toast=''},1500)}
async function requestAvailability(){if(!S.authenticated){requestState={type:'warning',text:'Open MAXINES inside Telegram to submit an authenticated availability request.'};render();return}const btn=$('#drawerAction');if(btn){btn.disabled=true;btn.textContent='Sending request…'}try{const res=await fetch('/api/request',{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':tg?.initData||''},body:JSON.stringify({items:bag.map(i=>({sku:i.sku,size:i.size||'OS',quantity:i.qty||1}))}),cache:'no-store'});const body=await res.json().catch(()=>null);if(!res.ok||!body?.request?.id)throw new Error(body?.error||'Request could not be sent.');requestState={type:'success',text:`Request ${String(body.request.id).slice(0,8)} received. No payment was taken and this is not a confirmed order.`};tg?.HapticFeedback?.notificationOccurred?.('success');render()}catch(e){requestState={type:'warning',text:String(e?.message||'Request could not be sent.')};render()}}
async function startCheckout(){if(!H.checkoutActivated){return requestAvailability()}if(!S.authenticated){requestState={type:'warning',text:'Open MAXINES inside Telegram to continue secure checkout.'};render();return}const btn=$('#drawerAction');if(btn){btn.disabled=true;btn.textContent='Preparing checkout…'}try{const res=await fetch('/api/checkout',{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':tg?.initData||''},body:JSON.stringify({items:bag.map(i=>({sku:i.sku,size:i.size||'OS',quantity:i.qty||1}))}),cache:'no-store'});const body=await res.json().catch(()=>null);if(!res.ok||!body?.invoiceUrl)throw new Error(body?.error||'Checkout could not be created.');if(!tg?.openInvoice)throw new Error('Open MAXINES inside Telegram to continue payment.');tg.openInvoice(body.invoiceUrl,status=>{requestState={type:status==='paid'?'success':'warning',text:`Invoice ${status}.`};if(status==='paid'){bag=[];saveBag()}render()})}catch(e){requestState={type:'warning',text:String(e?.message||'Checkout could not be created.')};render()}}
function wireHome(){$('#searchBtn')?.addEventListener('click',()=>{searchOpen=true;render();requestAnimationFrame(()=>$('#searchInput')?.focus())});$('#searchClose')?.addEventListener('click',()=>{searchOpen=false;q='';render()});$('#searchInput')?.addEventListener('input',e=>{q=e.target.value;render();requestAnimationFrame(()=>{const x=$('#searchInput');x?.focus();x?.setSelectionRange(q.length,q.length)})});$('#bagBtn')?.addEventListener('click',()=>{showBag=true;syncBack();render()});$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openProduct(product(b.dataset.open))));$('#pdpBack')?.addEventListener('click',closeOverlay);$$('[data-media]').forEach(b=>b.addEventListener('click',()=>{mediaMode=b.dataset.media;render()}));$('#addSelection')?.addEventListener('click',()=>addToBag(open));$('#openBagFromPdp')?.addEventListener('click',()=>{addToBag(open)});$('#drawerClose')?.addEventListener('click',closeOverlay);$('#drawerBackdrop')?.addEventListener('click',e=>{if(e.target.id==='drawerBackdrop')closeOverlay()});$$('[data-qty]').forEach(b=>b.addEventListener('click',()=>{const n=Number(b.dataset.i),d=Number(b.dataset.qty);bag[n].qty=(bag[n].qty||1)+d;if(bag[n].qty<=0)bag.splice(n,1);saveBag();render()}));$('#drawerAction')?.addEventListener('click',startCheckout)}
function render(){if(!entered)return renderLanding();renderHome()}
try{tg?.ready();tg?.expand();tg?.setHeaderColor?.('#FDFCF8');tg?.setBackgroundColor?.('#FDFCF8');document.documentElement.dataset.theme='light'}catch{}syncBack();render();
