import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const ALLOWED_ORIGIN="https://maxines.vercel.app";
const MAX_INIT_AGE_SECONDS=3600;
const enc=new TextEncoder(),dec=new TextDecoder();

function headers(){return{"Access-Control-Allow-Origin":ALLOWED_ORIGIN,"Access-Control-Allow-Headers":"content-type,x-telegram-init-data,x-maxines-session","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Cache-Control":"no-store","Vary":"Origin","X-Content-Type-Options":"nosniff"}}
function json(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...headers(),"Content-Type":"application/json; charset=utf-8"}})}
async function rest(path:string,init:RequestInit={}){if(!SUPABASE_URL||!SERVICE_ROLE_KEY)throw new Error("database_not_configured");const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,Accept:"application/json","Content-Type":"application/json",...(init.headers||{})}});const text=await r.text();let data:any=null;if(text){try{data=JSON.parse(text)}catch{data=text}}if(!r.ok)throw new Error(`database_${r.status}`);return data}
async function rpc(name:string,body:Record<string,unknown>={}){return await rest(`rpc/${name}`,{method:"POST",body:JSON.stringify(body)})}
function firstString(v:any){if(typeof v==="string")return v;if(Array.isArray(v)&&typeof v[0]==="string")return v[0];if(v&&typeof v==="object"){const x=Object.values(v)[0];if(typeof x==="string")return x}return""}
async function botToken(){return firstString(await rpc("maxines_get_telegram_bot_token"))}
async function hmac(keyBytes:Uint8Array,message:string){const key=await crypto.subtle.importKey("raw",keyBytes,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(message)))}
function hex(bytes:Uint8Array){return Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("")}
function constantTime(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function b64url(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function b64urlDecode(s:string){const p=s.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-s.length%4)%4),raw=atob(p);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function sessionKey(){const token=await botToken();if(!token)throw new Error("bot_not_configured");return await hmac(enc.encode(token),"MAXINES_SESSION_V1")}
async function validateSession(raw:string){try{const [body,sig,...extra]=raw.split('.');if(!body||!sig||extra.length)return{ok:false,error:"invalid_session"}as const;const expected=b64url(await hmac(await sessionKey(),body));if(!constantTime(expected,sig))return{ok:false,error:"invalid_session"}as const;const p=JSON.parse(dec.decode(b64urlDecode(body))),now=Math.floor(Date.now()/1000);if(p?.v!==1||!p?.user?.id||!Number.isFinite(p?.exp)||p.exp<now)return{ok:false,error:"expired_session"}as const;return{ok:true,user:p.user,staffRole:typeof p.staffRole==="string"?p.staffRole:null}as const}catch{return{ok:false,error:"invalid_session"}as const}}
async function validateInit(raw:string){if(!raw)return{ok:false,error:"missing_init_data"}as const;const token=await botToken();if(!token)return{ok:false,error:"bot_not_configured"}as const;const p=new URLSearchParams(raw),received=(p.get("hash")||"").toLowerCase();if(!/^[0-9a-f]{64}$/.test(received))return{ok:false,error:"invalid_hash"}as const;p.delete("hash");const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n"),secret=await hmac(enc.encode("WebAppData"),token),expected=hex(await hmac(secret,check));if(!constantTime(expected,received))return{ok:false,error:"signature_mismatch"}as const;const authDate=Number(p.get("auth_date")),now=Math.floor(Date.now()/1000);if(!Number.isFinite(authDate)||authDate>now+60||now-authDate>MAX_INIT_AGE_SECONDS)return{ok:false,error:"expired_init_data"}as const;let u:any=null;try{u=JSON.parse(p.get("user")||"null")}catch{}if(!u?.id)return{ok:false,error:"missing_user"}as const;return{ok:true,user:{id:Number(u.id),username:typeof u.username==="string"?u.username:null,firstName:typeof u.first_name==="string"?u.first_name:null,lastName:typeof u.last_name==="string"?u.last_name:null}}as const}
async function authenticate(req:Request){const s=req.headers.get("x-maxines-session")||"";if(s){const x=await validateSession(s);if(x.ok)return x}return await validateInit(req.headers.get("x-telegram-init-data")||"")}
function normalize(raw:any){if(!Array.isArray(raw)||raw.length<1||raw.length>20)throw new Error("invalid_items");const m=new Map<string,{sku:string,size:string,quantity:number}>();for(const item of raw){const sku=String(item?.sku||"").trim().toUpperCase(),size=String(item?.size||"OS").trim().toUpperCase(),quantity=Number(item?.quantity);if(!/^[A-Z0-9-]{2,40}$/.test(sku)||!/^[A-Z0-9+._-]{1,16}$/.test(size)||!Number.isInteger(quantity)||quantity<1||quantity>10)throw new Error("invalid_item");const k=`${sku}::${size}`,x=m.get(k);if(x){x.quantity+=quantity;if(x.quantity>10)throw new Error("invalid_quantity")}else m.set(k,{sku,size,quantity})}return[...m.values()]}
async function send(chatId:number,text:string){try{const token=await botToken();if(!token)return;await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text})})}catch{}}
async function notifyCustomer(chatId:number,requestId:string){await send(chatId,`MAXINES availability request ${requestId.slice(0,8)} received. This is not a confirmed order and no payment was taken. We will keep the request on file until availability and live pricing are verified.`)}
async function notifyStaff(requestId:string,user:any,items:any[]){try{const rows=await rest("staff_users?select=telegram_user_id,role&active=eq.true&role=in.(owner,admin,staff)");const who=user.username?`@${user.username}`:`Telegram ${user.id}`;const summary=items.map(i=>`${i.sku}/${i.size} ×${i.quantity}`).join(', ');await Promise.all(rows.map((r:any)=>send(Number(r.telegram_user_id),`MAXINES request ${requestId.slice(0,8)} from ${who}: ${summary}`)))}catch{}}
async function audit(userId:number,eventName:string,entityId:string,metadata:any){try{await rpc("maxines_record_audit",{p_actor_telegram_user_id:String(userId),p_actor_role:null,p_event_name:eventName,p_entity_type:"availability_request",p_entity_id:entityId,p_metadata:metadata})}catch{}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:headers()});try{const auth=await authenticate(req);if(!auth.ok)return json(401,{ok:false,error:"telegram_auth_required"});if(req.method==="POST"){const body=await req.json().catch(()=>({})),items=normalize(body?.items);const created=await rpc("create_availability_request",{p_telegram_user_id:String(auth.user.id),p_telegram_username:auth.user.username,p_telegram_first_name:auth.user.firstName,p_telegram_last_name:auth.user.lastName,p_items:items}),row=Array.isArray(created)?created[0]:created;if(!row?.request_id)throw new Error("request_not_created");await Promise.all([notifyCustomer(auth.user.id,String(row.request_id)),notifyStaff(String(row.request_id),auth.user,items),audit(auth.user.id,"availability_request_created",String(row.request_id),{items:items.length})]);return json(200,{ok:true,request:{id:row.request_id,status:row.request_status,createdAt:row.request_created_at},charged:false,confirmedOrder:false})}if(req.method==="GET"){const rows=await rest(`availability_requests?select=id,status,items,created_at,updated_at&telegram_user_id=eq.${encodeURIComponent(String(auth.user.id))}&order=created_at.desc&limit=20`);return json(200,{ok:true,requests:rows,charged:false})}return json(405,{ok:false,error:"method_not_allowed"})}catch(e){console.error("maxines-request",e instanceof Error?e.message:"unknown_error");const msg=e instanceof Error?e.message:"request_failed";return json(/invalid|unknown/.test(msg)?400:503,{ok:false,error:/invalid|unknown/.test(msg)?msg:"request_unavailable"})}});
