import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const ALLOWED_ORIGIN="https://maxines.vercel.app";
const MAX_INIT_AGE_SECONDS=3600;
const enc=new TextEncoder();

function headers(){return{"Access-Control-Allow-Origin":ALLOWED_ORIGIN,"Access-Control-Allow-Headers":"content-type,x-telegram-init-data","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Cache-Control":"no-store","Vary":"Origin","X-Content-Type-Options":"nosniff"}}
function json(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...headers(),"Content-Type":"application/json; charset=utf-8"}})}
async function rest(path:string,init:RequestInit={}){if(!SUPABASE_URL||!SERVICE_ROLE_KEY)throw new Error("database_not_configured");const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,Accept:"application/json","Content-Type":"application/json",...(init.headers||{})}});const text=await r.text();let data:any=null;if(text){try{data=JSON.parse(text)}catch{data=text}}if(!r.ok)throw new Error(`database_${r.status}`);return data}
async function rpc(name:string,body:Record<string,unknown>={}){return await rest(`rpc/${name}`,{method:"POST",body:JSON.stringify(body)})}
function firstString(v:any){if(typeof v==="string")return v;if(Array.isArray(v)&&typeof v[0]==="string")return v[0];if(v&&typeof v==="object"){const x=Object.values(v)[0];if(typeof x==="string")return x}return""}
async function botToken(){return firstString(await rpc("maxines_get_telegram_bot_token"))}
async function hmac(keyBytes:Uint8Array,message:string){const key=await crypto.subtle.importKey("raw",keyBytes,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(message)))}
function hex(bytes:Uint8Array){return Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("")}
function constantTime(a:string,b:string){if(a.length!==b.length||a.length!==64)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function validate(raw:string){if(!raw)return{ok:false,error:"missing_init_data"}as const;const token=await botToken();if(!token)return{ok:false,error:"bot_not_configured"}as const;const p=new URLSearchParams(raw);const received=(p.get("hash")||"").toLowerCase();if(!/^[0-9a-f]{64}$/.test(received))return{ok:false,error:"invalid_hash"}as const;p.delete("hash");const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n");const secret=await hmac(enc.encode("WebAppData"),token);const expected=hex(await hmac(secret,check));if(!constantTime(expected,received))return{ok:false,error:"signature_mismatch"}as const;const authDate=Number(p.get("auth_date"));const now=Math.floor(Date.now()/1000);if(!Number.isFinite(authDate)||authDate>now+60||now-authDate>MAX_INIT_AGE_SECONDS)return{ok:false,error:"expired_init_data"}as const;let u:any=null;try{u=JSON.parse(p.get("user")||"null")}catch{}if(!u?.id)return{ok:false,error:"missing_user"}as const;return{ok:true,user:{id:Number(u.id),username:typeof u.username==="string"?u.username:null,firstName:typeof u.first_name==="string"?u.first_name:null,lastName:typeof u.last_name==="string"?u.last_name:null}}as const}
function normalize(raw:any){if(!Array.isArray(raw)||raw.length<1||raw.length>20)throw new Error("invalid_items");const m=new Map<string,{sku:string,size:string,quantity:number}>();for(const item of raw){const sku=String(item?.sku||"").trim().toUpperCase(),size=String(item?.size||"OS").trim().toUpperCase(),quantity=Number(item?.quantity);if(!/^[A-Z0-9-]{2,40}$/.test(sku)||!/^[A-Z0-9+._-]{1,16}$/.test(size)||!Number.isInteger(quantity)||quantity<1||quantity>10)throw new Error("invalid_item");const k=`${sku}::${size}`,x=m.get(k);if(x){x.quantity+=quantity;if(x.quantity>10)throw new Error("invalid_quantity")}else m.set(k,{sku,size,quantity})}return[...m.values()]}
async function notify(chatId:number,requestId:string){try{const token=await botToken();if(!token)return;await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text:`MAXINES availability request ${requestId.slice(0,8)} received. This is not a confirmed order and no payment was taken. We will keep the request on file until availability and live pricing are verified.`})})}catch{}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:headers()});try{const auth=await validate(req.headers.get("x-telegram-init-data")||"");if(!auth.ok)return json(401,{ok:false,error:"telegram_auth_required"});if(req.method==="POST"){const body=await req.json().catch(()=>({}));const items=normalize(body?.items);const created=await rpc("create_availability_request",{p_telegram_user_id:String(auth.user.id),p_telegram_username:auth.user.username,p_telegram_first_name:auth.user.firstName,p_telegram_last_name:auth.user.lastName,p_items:items});const row=Array.isArray(created)?created[0]:created;if(!row?.request_id)throw new Error("request_not_created");await notify(auth.user.id,String(row.request_id));return json(200,{ok:true,request:{id:row.request_id,status:row.request_status,createdAt:row.request_created_at},charged:false,confirmedOrder:false})}if(req.method==="GET"){const rows=await rest(`availability_requests?select=id,status,items,created_at,updated_at&telegram_user_id=eq.${encodeURIComponent(String(auth.user.id))}&order=created_at.desc&limit=20`);return json(200,{ok:true,requests:rows,charged:false})}return json(405,{ok:false,error:"method_not_allowed"})}catch(e){console.error("maxines-request",e instanceof Error?e.message:"unknown_error");const msg=e instanceof Error?e.message:"request_failed";return json(/invalid|unknown/.test(msg)?400:503,{ok:false,error:/invalid|unknown/.test(msg)?msg:"request_unavailable"})}});
