import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const APP_URL="https://maxines.vercel.app";
const enc=new TextEncoder();

function json(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}})}
async function rest(path:string,init:RequestInit={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,"content-type":"application/json",accept:"application/json",...(init.headers||{})}});const t=await r.text();let d:any=null;if(t){try{d=JSON.parse(t)}catch{d=t}}if(!r.ok)throw new Error(`database_${r.status}`);return d}
async function rpc(name:string,body:Record<string,unknown>={}){return await rest(`rpc/${name}`,{method:"POST",body:JSON.stringify(body)})}
function firstString(v:any){if(typeof v==="string")return v;if(Array.isArray(v)&&typeof v[0]==="string")return v[0];if(v&&typeof v==="object"){const x=Object.values(v)[0];if(typeof x==="string")return x}return ""}
function constantTimeEqual(a:string,b:string){const aa=enc.encode(a),bb=enc.encode(b);if(aa.length!==bb.length||aa.length===0)return false;let diff=0;for(let i=0;i<aa.length;i++)diff|=aa[i]^bb[i];return diff===0}
async function botToken(){return firstString(await rpc("maxines_get_telegram_bot_token"))}
async function webhookSecret(){return firstString(await rpc("maxines_get_telegram_webhook_secret"))}
async function telegram(method:string,body:Record<string,unknown>){const token=await botToken();if(!token)throw new Error("telegram_not_configured");const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(`telegram_${method}_failed`);return d.result}
async function settings(){const rows=await rest("commerce_settings?select=checkout_release_authorized,payment_currency,flat_shipping_amount&singleton=eq.true&limit=1");return rows?.[0]||{checkout_release_authorized:false}}
async function capabilities(){return await rpc("maxines_backend_capabilities")}
function command(update:any){const text=update?.message?.text;if(typeof text!=="string")return null;return text.trim().split(/\s+/)[0]?.split("@")[0]?.toLowerCase()||null}
async function sendCommandReply(update:any){const chatId=update?.message?.chat?.id;if(!chatId)return;const cmd=command(update);if(!["/start","/shop","/help"].includes(cmd||""))return;const text=cmd==="/help"?"Use /shop or Shop MAXINES to open the store. Payments remain unavailable until verified inventory, settlement pricing, shipping, provider credentials, and release authorization are all active.":"Welcome to MAXINES. Open the private shop below to browse the verified collection.";await telegram("sendMessage",{chat_id:chatId,text,disable_web_page_preview:true,reply_markup:{inline_keyboard:[[{text:"Open MAXINES",web_app:{url:APP_URL}}]]}})}
async function handlePreCheckout(update:any){const q=update?.pre_checkout_query;if(!q?.id)return;const [caps,cfg]=await Promise.all([capabilities(),settings()]);if(!caps?.payment_provider_configured||!cfg?.checkout_release_authorized){await telegram("answerPreCheckoutQuery",{pre_checkout_query_id:q.id,ok:false,error_message:"MAXINES checkout is not active yet."});return}const result=await rpc("validate_precheckout",{p_order_id:String(q.invoice_payload||""),p_currency:String(q.currency||""),p_total_amount:Number(q.total_amount||0)});const row=Array.isArray(result)?result[0]:result;const ok=Boolean(row?.ok);const body:any={pre_checkout_query_id:q.id,ok};if(!ok)body.error_message=String(row?.reason||"This order is no longer available. Please reopen MAXINES and try again.").slice(0,200);await telegram("answerPreCheckoutQuery",body)}
async function handleSuccessfulPayment(update:any){const message=update?.message;const p=message?.successful_payment;if(!p)return false;const orderId=String(p.invoice_payload||"");if(!/^[0-9a-f-]{36}$/i.test(orderId))throw new Error("invalid_paid_order_id");await rpc("complete_order_payment",{p_order_id:orderId,p_currency:String(p.currency||""),p_total_amount:Number(p.total_amount||0),p_telegram_charge_id:String(p.telegram_payment_charge_id||""),p_provider_charge_id:String(p.provider_payment_charge_id||""),p_raw_payment:{telegram_payment_received:true}});if(message?.chat?.id){try{await telegram("sendMessage",{chat_id:message.chat.id,text:`MAXINES payment confirmed. Order ${orderId.slice(0,8)} is now paid.`,disable_web_page_preview:true})}catch{}}return true}

Deno.serve(async(req)=>{if(req.method!=="POST")return json(405,{ok:false,error:"method_not_allowed"});try{const expected=await webhookSecret();const received=req.headers.get("x-telegram-bot-api-secret-token")||"";if(!constantTimeEqual(received,expected))return json(401,{ok:false,error:"unauthorized"});const update=await req.json().catch(()=>null);if(!update||typeof update.update_id!=="number")return json(400,{ok:false,error:"invalid_update"});if(update.pre_checkout_query)await handlePreCheckout(update);else if(await handleSuccessfulPayment(update)){}else if(update.message)await sendCommandReply(update);return json(200,{ok:true})}catch(error){console.error("maxines-telegram-webhook",error instanceof Error?error.message:"unknown_error");return json(500,{ok:false,error:"webhook_processing_failed"})}});
