import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const ALLOWED_ORIGIN="https://maxines.vercel.app";
const MAX_INIT_AGE_SECONDS=3600;
const SESSION_TTL_SECONDS=1800;
const enc=new TextEncoder(),dec=new TextDecoder();

function cors(origin:string|null){return{"Access-Control-Allow-Origin":origin===ALLOWED_ORIGIN?ALLOWED_ORIGIN:ALLOWED_ORIGIN,"Access-Control-Allow-Headers":"content-type,x-telegram-init-data,x-maxines-session","Access-Control-Allow-Methods":"GET,POST,DELETE,OPTIONS","Cache-Control":"no-store","Vary":"Origin","X-Content-Type-Options":"nosniff"}}
function json(status:number,body:unknown,origin:string|null){return new Response(JSON.stringify(body),{status,headers:{...cors(origin),"Content-Type":"application/json; charset=utf-8"}})}
async function rest(path:string,init:RequestInit={}){if(!SUPABASE_URL||!SERVICE_ROLE_KEY)throw new Error("database_not_configured");const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,Accept:"application/json","Content-Type":"application/json",...(init.headers||{})}});const text=await r.text();let data:any=null;if(text){try{data=JSON.parse(text)}catch{data=text}}if(!r.ok){const e=new Error(`database_${r.status}`);(e as any).details=data;throw e}return data}
async function rpc(name:string,body:Record<string,unknown>={}){return await rest(`rpc/${name}`,{method:"POST",body:JSON.stringify(body)})}
function firstString(v:any){if(typeof v==="string")return v;if(Array.isArray(v)&&typeof v[0]==="string")return v[0];if(v&&typeof v==="object"){const x=Object.values(v)[0];if(typeof x==="string")return x}return""}
async function botToken(){return firstString(await rpc("maxines_get_telegram_bot_token"))}
async function paymentProviderToken(){return firstString(await rpc("maxines_get_payment_provider_token"))}
async function settings(){const rows=await rest("commerce_settings?select=checkout_release_authorized,payment_currency,flat_shipping_amount&singleton=eq.true&limit=1");return rows?.[0]||{checkout_release_authorized:false,payment_currency:null,flat_shipping_amount:null}}
async function capabilities(){return await rpc("maxines_backend_capabilities")}
async function telegram(method:string,body:Record<string,unknown>){const token=await botToken();if(!token)throw new Error("telegram_not_configured");const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await r.json().catch(()=>null);if(!r.ok||!data?.ok)throw new Error(`telegram_${method}_failed`);return data.result}
async function hmac(keyBytes:Uint8Array,message:string){const key=await crypto.subtle.importKey("raw",keyBytes,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(message)))}
function hex(bytes:Uint8Array){return Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("")}
function constantTime(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function b64url(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function b64urlDecode(s:string){const p=s.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-s.length%4)%4);const raw=atob(p);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function sessionKey(){const token=await botToken();if(!token)throw new Error("bot_not_configured");return await hmac(enc.encode(token),"MAXINES_SESSION_V1")}
async function signSession(user:any,staffRole:string|null){const now=Math.floor(Date.now()/1000);const payload={v:1,iat:now,exp:now+SESSION_TTL_SECONDS,user,staffRole:staffRole||null};const body=b64url(enc.encode(JSON.stringify(payload)));const sig=b64url(await hmac(await sessionKey(),body));return `${body}.${sig}`}
async function validateSession(raw:string){try{const [body,sig,...restParts]=raw.split('.');if(!body||!sig||restParts.length)return{ok:false,error:"invalid_session"}as const;const expected=b64url(await hmac(await sessionKey(),body));if(!constantTime(expected,sig))return{ok:false,error:"invalid_session"}as const;const payload=JSON.parse(dec.decode(b64urlDecode(body)));const now=Math.floor(Date.now()/1000);if(payload?.v!==1||!payload?.user?.id||!Number.isFinite(payload?.exp)||payload.exp<now)return{ok:false,error:"expired_session"}as const;return{ok:true,user:payload.user,staffRole:typeof payload.staffRole==="string"?payload.staffRole:null}as const}catch{return{ok:false,error:"invalid_session"}as const}}
async function validateTelegramInitData(raw:string){if(!raw)return{ok:false,error:"missing_init_data"}as const;const token=await botToken();if(!token)return{ok:false,error:"bot_not_configured"}as const;const p=new URLSearchParams(raw),received=(p.get("hash")||"").toLowerCase();if(!/^[0-9a-f]{64}$/.test(received))return{ok:false,error:"invalid_hash"}as const;p.delete("hash");const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n");const secret=await hmac(enc.encode("WebAppData"),token),expected=hex(await hmac(secret,check));if(!constantTime(expected,received))return{ok:false,error:"signature_mismatch"}as const;const authDate=Number(p.get("auth_date")),now=Math.floor(Date.now()/1000);if(!Number.isFinite(authDate))return{ok:false,error:"missing_auth_date"}as const;if(authDate>now+60)return{ok:false,error:"future_auth_date"}as const;if(now-authDate>MAX_INIT_AGE_SECONDS)return{ok:false,error:"expired_init_data"}as const;let u:any=null;try{u=JSON.parse(p.get("user")||"null")}catch{}if(!u?.id)return{ok:false,error:"missing_user"}as const;return{ok:true,user:{id:Number(u.id),username:typeof u.username==="string"?u.username:null,firstName:typeof u.first_name==="string"?u.first_name:null,lastName:typeof u.last_name==="string"?u.last_name:null,languageCode:typeof u.language_code==="string"?u.language_code:null}}as const}
async function staffRole(userId:number){const rows=await rest(`staff_users?select=role&telegram_user_id=eq.${encodeURIComponent(String(userId))}&active=eq.true&limit=1`);return typeof rows?.[0]?.role==="string"?rows[0].role:null}
async function authenticate(req:Request){const s=req.headers.get("x-maxines-session")||"";if(s){const auth=await validateSession(s);if(auth.ok)return auth}const t=await validateTelegramInitData(req.headers.get("x-telegram-init-data")||"");if(!t.ok)return t;return{...t,staffRole:await staffRole(t.user.id)}as const}
function normalizeItems(raw:any){if(!Array.isArray(raw)||raw.length<1||raw.length>20)throw new Error("invalid_items");const m=new Map<string,{sku:string,size:string,quantity:number}>();for(const item of raw){const sku=String(item?.sku||"").trim().toUpperCase(),size=String(item?.size||"OS").trim().toUpperCase(),quantity=Number(item?.quantity);if(!/^[A-Z0-9-]{2,40}$/.test(sku)||!/^[A-Z0-9+._-]{1,16}$/.test(size)||!Number.isInteger(quantity)||quantity<1||quantity>10)throw new Error("invalid_item");const k=`${sku}::${size}`,x=m.get(k);if(x){x.quantity+=quantity;if(x.quantity>10)throw new Error("invalid_quantity")}else m.set(k,{sku,size,quantity})}return[...m.values()]}
async function audit(userId:number|null,role:string|null,eventName:string,entityType:string|null=null,entityId:string|null=null,metadata:any={}){try{await rpc("maxines_record_audit",{p_actor_telegram_user_id:userId?String(userId):null,p_actor_role:role,p_event_name:eventName,p_entity_type:entityType,p_entity_id:entityId,p_metadata:metadata})}catch{}}
async function cancelOrder(orderId:string){try{await rpc("cancel_checkout_order",{p_order_id:orderId})}catch{}}

Deno.serve(async req=>{
  const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});const url=new URL(req.url),route=url.pathname.split("/").filter(Boolean).pop()||"health";
  try{
    if(route==="health"&&req.method==="GET"){
      const [products,variants,caps,cfg]=await Promise.all([rest("products?select=sku,checkout_enabled&active=eq.true"),rest("product_variants?select=stock,enabled&enabled=eq.true"),capabilities(),settings()]);
      const checkoutEnabledProducts=products.filter((p:any)=>p.checkout_enabled).length,inventoryConfigured=variants.some((v:any)=>Number(v.stock)>0);const checkoutActivated=Boolean(caps?.payment_provider_configured&&cfg.checkout_release_authorized&&cfg.payment_currency&&cfg.flat_shipping_amount!==null&&checkoutEnabledProducts>0&&inventoryConfigured);
      return json(200,{ok:true,app:"maxines",ready:true,catalogSize:products.length,checkoutActivated,mode:"full_backend_fail_closed"},origin);
    }
    if(route==="catalog"&&req.method==="GET"){
      const [products,variants]=await Promise.all([rest("products?select=id,sku,name,category,display_price,display_currency,tag,description,source_verified,checkout_enabled,sort_order&active=eq.true&order=sort_order.asc"),rest("product_variants?select=product_id,size,stock,enabled&enabled=eq.true&order=size.asc")]);const by=new Map<string,any[]>();for(const v of variants){if(!by.has(v.product_id))by.set(v.product_id,[]);by.get(v.product_id)!.push({size:v.size,enabled:Boolean(v.enabled),inStock:Number(v.stock)>0})}return json(200,{ok:true,products:products.map((p:any)=>({sku:p.sku,name:p.name,category:p.category,displayPrice:Number(p.display_price),displayCurrency:p.display_currency,tag:p.tag||"",description:p.description||"",sourceVerified:Boolean(p.source_verified),checkoutEnabled:Boolean(p.checkout_enabled),variants:by.get(p.id)||[]})),source:{mode:"supabase_database",availableItems:products.length,exactStockCountsExposed:false}},origin);
    }
    if(route==="session"){
      if(req.method==="POST"){
        const auth=await validateTelegramInitData(req.headers.get("x-telegram-init-data")||"");if(!auth.ok)return json(401,{ok:false,authenticated:false,error:auth.error},origin);const role=await staffRole(auth.user.id),sessionToken=await signSession(auth.user,role);await audit(auth.user.id,role,"session_started","session",null,{telegram:true});return json(200,{ok:true,authenticated:true,telegram:true,user:auth.user,staffRole:role,sessionToken,sessionMaxAge:SESSION_TTL_SECONDS},origin);
      }
      if(req.method==="GET"){
        const auth=await validateSession(req.headers.get("x-maxines-session")||"");if(!auth.ok)return json(401,{ok:false,authenticated:false,error:auth.error},origin);return json(200,{ok:true,authenticated:true,telegram:true,user:auth.user,staffRole:auth.staffRole||null},origin);
      }
    }
    if(route==="telegram-health"&&req.method==="GET"){const bot=await telegram("getMe",{});return json(200,{ok:true,reason:"connected",username:bot?.username||null,id:bot?.id||null},origin)}
    if(route==="favorites"){
      const auth=await authenticate(req);if(!auth.ok)return json(401,{ok:false,error:"telegram_auth_required"},origin);
      if(req.method==="GET"){const rows=await rest(`user_favorites?select=sku,created_at&telegram_user_id=eq.${encodeURIComponent(String(auth.user.id))}&order=created_at.desc`);return json(200,{ok:true,favorites:rows.map((r:any)=>r.sku)},origin)}
      const body=await req.json().catch(()=>({})),sku=String(body?.sku||url.searchParams.get("sku")||"").trim().toUpperCase();if(!/^[A-Z0-9-]{2,40}$/.test(sku))return json(400,{ok:false,error:"invalid_sku"},origin);
      if(req.method==="POST"){const p=await rest(`products?select=sku&sku=eq.${encodeURIComponent(sku)}&active=eq.true&limit=1`);if(!p?.[0])return json(404,{ok:false,error:"product_not_found"},origin);await rest("user_favorites?on_conflict=telegram_user_id,sku",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({telegram_user_id:auth.user.id,sku})});await audit(auth.user.id,auth.staffRole||null,"favorite_added","product",sku,{});return json(200,{ok:true,saved:true,sku},origin)}
      if(req.method==="DELETE"){await rest(`user_favorites?telegram_user_id=eq.${encodeURIComponent(String(auth.user.id))}&sku=eq.${encodeURIComponent(sku)}`,{method:"DELETE"});await audit(auth.user.id,auth.staffRole||null,"favorite_removed","product",sku,{});return json(200,{ok:true,saved:false,sku},origin)}
    }
    if(route==="orders"&&req.method==="GET"){
      const auth=await authenticate(req);if(!auth.ok)return json(401,{ok:false,error:"telegram_auth_required"},origin);const rows=await rest(`orders?select=id,status,currency,subtotal_amount,shipping_amount,total_amount,created_at,paid_at&telegram_user_id=eq.${encodeURIComponent(String(auth.user.id))}&order=created_at.desc&limit=20`);return json(200,{ok:true,orders:rows},origin);
    }
    if(route==="owner-requests"){
      const auth=await authenticate(req);if(!auth.ok)return json(401,{ok:false,error:"telegram_auth_required"},origin);const currentRole=await staffRole(auth.user.id);if(!['owner','admin','staff'].includes(currentRole||''))return json(403,{ok:false,error:"staff_required"},origin);
      if(req.method==="GET"){const rows=await rest("availability_requests?select=id,telegram_user_id,telegram_username,telegram_first_name,items,status,created_at,updated_at&order=created_at.desc&limit=50");return json(200,{ok:true,requests:rows},origin)}
      if(req.method==="POST"){const body=await req.json().catch(()=>({})),id=String(body?.id||""),status=String(body?.status||"");if(!/^[0-9a-f-]{36}$/i.test(id)||!['pending','reviewing','contacted','closed','cancelled'].includes(status))return json(400,{ok:false,error:"invalid_owner_request_update"},origin);const rows=await rest(`availability_requests?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status,updated_at:new Date().toISOString()})});if(!rows?.[0])return json(404,{ok:false,error:"request_not_found"},origin);await audit(auth.user.id,currentRole||null,"availability_request_status_changed","availability_request",id,{status});return json(200,{ok:true,request:rows[0]},origin)}
    }
    if(route==="checkout"&&req.method==="POST"){
      const auth=await authenticate(req);if(!auth.ok)return json(401,{ok:false,error:"telegram_auth_required"},origin);const [caps,cfg]=await Promise.all([capabilities(),settings()]);if(!caps?.payment_provider_configured)return json(503,{ok:false,error:"payment_provider_not_configured",checkoutActivated:false},origin);if(!cfg.checkout_release_authorized)return json(503,{ok:false,error:"checkout_release_not_authorized",checkoutActivated:false},origin);if(!cfg.payment_currency)return json(503,{ok:false,error:"payment_currency_not_configured",checkoutActivated:false},origin);if(cfg.flat_shipping_amount===null)return json(503,{ok:false,error:"shipping_not_configured",checkoutActivated:false},origin);const body=await req.json().catch(()=>({})),items=normalizeItems(body?.items);let orderId="";try{const created=await rpc("create_checkout_order",{p_telegram_user_id:String(auth.user.id),p_currency:cfg.payment_currency,p_items:items,p_shipping_amount:Number(cfg.flat_shipping_amount)}),order=Array.isArray(created)?created[0]:created;if(!order?.order_id)throw new Error("order_not_created");orderId=order.order_id;const providerToken=await paymentProviderToken();if(!providerToken)throw new Error("payment_provider_not_configured");const prices:any[]=[{label:"Merchandise",amount:Number(order.subtotal_amount)}];if(Number(order.shipping_amount)>0)prices.push({label:"Shipping",amount:Number(order.shipping_amount)});const invoiceUrl=await telegram("createInvoiceLink",{title:"MAXINES Order",description:`MAXINES order ${orderId.slice(0,8)} — ${items.reduce((n:number,i:any)=>n+i.quantity,0)} piece(s)`,payload:orderId,provider_token:providerToken,currency:cfg.payment_currency,prices,need_name:true,need_phone_number:true,need_email:true,need_shipping_address:true,send_phone_number_to_provider:true,send_email_to_provider:true,is_flexible:false});await audit(auth.user.id,auth.staffRole||null,"checkout_created","order",orderId,{items:items.length});return json(200,{ok:true,mode:"telegram",orderId,invoiceUrl,currency:cfg.payment_currency,totalAmount:Number(order.total_amount)},origin)}catch(error){if(orderId)await cancelOrder(orderId);const msg=error instanceof Error?error.message:"checkout_failed",safe=/stock|variant|price|checkout|inventory|currency|shipping|payment_provider/i.test(msg)?msg:"checkout_could_not_be_created";await audit(auth.user.id,auth.staffRole||null,"checkout_failed",orderId?"order":null,orderId||null,{reason:safe});return json(409,{ok:false,error:safe},origin)}}
    if(route==="order"&&req.method==="GET"){const auth=await authenticate(req);if(!auth.ok)return json(401,{ok:false,error:"telegram_auth_required"},origin);const id=String(url.searchParams.get("id")||"");if(!/^[0-9a-f-]{36}$/i.test(id))return json(400,{ok:false,error:"invalid_order_id"},origin);const rows=await rest(`orders?select=id,status,currency,subtotal_amount,shipping_amount,total_amount,created_at,paid_at&id=eq.${encodeURIComponent(id)}&telegram_user_id=eq.${encodeURIComponent(String(auth.user.id))}&limit=1`);if(!rows?.[0])return json(404,{ok:false,error:"order_not_found"},origin);return json(200,{ok:true,order:rows[0]},origin)}
    return json(404,{ok:false,error:"not_found"},origin);
  }catch(error){console.error("maxines-api",error instanceof Error?error.message:"unknown_error");return json(503,{ok:false,error:"backend_unavailable"},origin)}
});
